# InfoBoardReloaded Config, Last Edited in v1.0.0
# =============================================================================
# |        Updater  - Checks for updates on enable                            |
# |---------------------------------------------------------------------------|
# |       Custom Variables allow for you to create your own variables         |
# |                  <Variable>: What it gets replaced to                     |
# |---------------------------------------------------------------------------|
# |     Disabled Worlds    - A List of worlds that won't have scoreboards     |
# | WorldGuard.Prevent Showing In - A List of regions the board won't show in |
# |---------------------------------------------------------------------------|
# | Scrolling Text is a cool feature where text will scroll across the board  |
# |                Currently format codes aren't supported                    |
# |       Shift Time - How long between the text scrolling in seconds         |
# |---------------------------------------------------------------------------|
# |                             Changeable text:                              |
# |                      Use like: <changeable_<variable>>                    |
# |                       Enabled- enable or disable                          |
# |                  Changeables - Custom changeable variables                |
# |	             interval- how fast the lines should update in seconds        | 
# |---------------------------------------------------------------------------|
# |          Update Time how fast you scoreboard updates in seconds           |
# =============================================================================
Updater: true
Debug: false

Custom Variables:
  <website>: yoursitehere.net
  <plugindev>: pixar02

Disabled Worlds:
- DisabledWorld1
- DisabledWorld2

WorldGuard:
  Prevent Showing In:
  - regionNamesAreCapSensitive
  - regionName2
  
Scrolling Text:
  Enable: false
  Shift Time: 0.25

Changeable Text:
  Enable: false   
  Changeables:
    healthloc:
      text:
      - '&a&lHealth: ; &e%player_health%&a/&c%player_max_health%'
      - '&5&lLocation: ; &a%player_x%&7, &a%player_y%&7, &a%player_z%'
      - '&e&lDate Joined: ; &l%player_first_join_date%'
      interval: 1 
        
Update Time:
  Lines: .5
  