# InfoBoardReloaded Config, Last Edited in v2.0.0
# =============================================================================
# |        Updater  - Checks for updates on enable                            |
# |---------------------------------------------------------------------------|
# |       Custom Variables allow for you to create your own variables         |
# |                  <Variable>: What it gets replaced to                     |
# |---------------------------------------------------------------------------|
//
# |     Disabled Worlds    - A List of worlds that won't have scoreboards     |
# | WorldGuard.Prevent Showing In - A List of regions the board won't show in |
# |---------------------------------------------------------------------------|
# | Scrolling Text is a cool feature where text will scroll across the board  |
# |                Currently format codes aren't supported                    |
# |       Shift Time - How long between the text scrolling in seconds         |
# |---------------------------------------------------------------------------|
# |                             Changeable text:                              |
# |                      Use like: <changeable_<variable>>                    |
# |                       Enabled- enable or disable                          |
# |                  Changeables - Custom changeable variables                |
# |                  Text - the text lines you want to display                |
# |	             interval- how fast the lines should update in seconds        | 
# |---------------------------------------------------------------------------|
# |          Update Time how fast you scoreboard updates in seconds           |
# =============================================================================
//
Updater: true
Debug: false

Custom Variables:
  <website>: yoursitehere.net
  <plugindev>: pixar02

  