name: InfoBoardReloaded
main: com.pixar02.infoboard.InfoBoardReloaded
version: 1.4.0
author: pixar02
description: Show a scoreboard
depend: [PlaceholderAPI, Vault, WorldGuard]

commands:
  InfoBoardReloaded:
    usage: /<command>
    description: The main command for this plugin
    aliases: [ibr, ib, iboard, infob, Infoboard]
    
permissions:
  ibr.*:
    default: op
    children:
      ibr.Set: true
      ibr.Toggle: true
      ibr.Reload: true
      ibr.View: true
  ibr.View:
    default: true
  ibr.Toggle:
    default: true